### ISSUE TITLE
It's already time to change the level, but next map is yet to be decided

### ISSUE THREAD

**Issue by MuerteInHell** [KirillMysnik/sp-map-cycle#1]
[SP] Caught an Exception: 

Traceback (most recent call last): 

File '../addons/source-python/packages/source-python/events/listener.py', line 92, in fire_game_event 

callback(game_event) 

File '../addons/source-python/plugins/sp_map_cycle/sp_map_cycle.py', line 1663, in on_round_end 

change_level(round_end=True) 

File '../addons/source-python/plugins/sp_map_cycle/sp_map_cycle.py', line 1532, in change_level 

raise RuntimeError('It's already time to change the level, ' 

RuntimeError: It's already time to change the level, but next map is yet to be decided

**Comment by KirillMysnik** [comment]
Thanks for your report! Found it.
The bug appeared when you ended the round after the map had been successfully changed via SP Map Cycle.
Besides spamming console with an exception every round end from then on, the bug had no other effects.

**Comment by KirillMysnik** [comment]
When ugrading to v1.1.0, please don't forget to delete your database.sqlite3 file.
https://github.com/KirillMysnik/sp-map-cycle/releases/tag/v1.1.0-beta.
